# Generated by Django 4.0.4 on 2022-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmimodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
