# Generated by Django 4.0.4 on 2022-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.CharField(default=True, max_length=3),
            preserve_default=False,
        ),
    ]
